name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      # Free more space for the UE Docker Image
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          build-mount-path: /var/lib/docker/
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Restart docker
        run: sudo service docker restart

      - uses: actions/checkout@v4
      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}
          registry: ghcr.io/epicgames
          image: unreal-engine:dev-slim-5.4.4
          options: -v "$PROJECT_PATH:/project"
          run: >
            /home/ue5/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh 
              BuildCookRun
              -utf8output
              -platform=Linux
              -clientconfig=Shipping
              -serverconfig=Shipping
              -project=/project/UE5_GHAction_VRTempl.uproject
              -noP4 -nodebuginfo -allmaps
              -cook -build -stage -prereqs -pak -archive
              -archivedirectory=/project/Packaged
