name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SSHFS
        run: sudo apt install sshfs
      - name: Create directory for mount
        run: mkdir ./ue/
      - name: Mount UE 5.4.4 install from a network drive
        env:
          USER: ${{ secrets.SSHFS_USER }}
          PASS: ${{ secrets.SSHFS_PASS }}
        run: >
          sshfs $USER@technicjelle@stack.technicjelle.com:/ue/Linux_Unreal_Engine_5.4.4/
          ./ue/
          -o allow_other
          -o reconnect
          -o StrictHostKeyChecking=no
          -o password_stdin <<< $PASS
      - name: Create directory for staging files
        run: mkdir ./staging/
      - name: Run UE5 build
        run: >
          bash $PWD/ue/Engine/Build/BatchFiles/RunUAT.sh -ScriptsForProject="$PWD/UE5_GHAction_VRTempl.uproject"
          BuildCookRun -project="$PWD/UE5_GHAction_VRTempl.uproject" -noP4
          -clientconfig=Shipping -serverconfig=Shipping -nocompile -nocompileeditor -installed
          -unrealexe="$PWD/ue/Engine/Binaries/Linux/UnrealEditor-Cmd" -utf8output
          -platform=Linux -build -cook
          -allmaps -CookCultures=en -unversionedcookedcontent -pak -stage
          -stagingdirectory="$PWD/staging/"
