name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SSHFS
        run: sudo apt install sshfs
      - name: Create directory for mount
        run: mkdir ./ue/
      - name: Uncomment option 'user_allow_other' in /etc/fuse.conf
        run: sudo sed -i -E 's/^#\s*(user_allow_other)/\1/' /etc/fuse.conf
      - name: Mount UE 5.4.4 install from a network drive
        env:
          USER: ${{ secrets.SSHFS_USER }}
          PASS: ${{ secrets.SSHFS_USER }}
        run: sshfs -o sshfs_debug $USER@technicjelle@stack.technicjelle.com:/ue/Linux_Unreal_Engine_5.4.4/ ./ue/ -o reconnect -o StrictHostKeyChecking=no -o allow_other,default_permissions -o password_stdin <<< $PASS
      - name: Tree
        run: tree
