name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install SSHFS
        run: sudo apt install sshfs
      - name: Create directory for mount
        run: mkdir ./ue/
      - name: Mount UE 5.4.4 install from a network drive
        run: sshfs -o sshfs_debug ${{ secrets.SSHFS_USER }}@technicjelle@stack.technicjelle.com:/ue/Linux_Unreal_Engine_5.4.4/ ./ue/ -o reconnect -o StrictHostKeyChecking=no -o password_stdin <<< '${{ secrets.SSHFS_USER }}'
      - name: Tree
        run: tree
