name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      # Free more space for the UE Docker Image
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          build-mount-path: /var/lib/docker/
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Restart docker
        run: sudo service docker restart

      - uses: actions/checkout@v4
      - name: Authenticate with GitHub Container Registry
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        run: echo $ACCESS_TOKEN | docker login ghcr.io -u $USERNAME --password-stdin
      - name: Docker Pull Prebuilt Container Image
        run: docker pull ghcr.io/epicgames/unreal-engine:dev-slim-5.4.4
      - name: Docker Run
        env:
          PROJECT_PATH: ${{ github.workspace }}
        run: docker run --rm -ti -v "$PROJECT_PATH:/project" ghcr.io/epicgames/unreal-engine:dev-slim-5.4.4
      - name: Build Project in Development Container
        run: echo "TODO"
