name: Build

on:
  push:
  workflow_dispatch:

env:
  RCLONE_NAME: stack
  RCLONE_MOUNT_POINT: /home/$USER/ue
  STAGING_DIR: $PWD/staging

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Install rclone
        run: sudo apt install rclone
      - name: Create directory for mount
        run: |
          sudo mkdir -m 700 ${{ env.RCLONE_MOUNT_POINT }}
          sudo chown $USER:$USER ${{ env.RCLONE_MOUNT_POINT }}
      - name: Configure rclone
        env:
          SSHFS_USER: ${{ secrets.SSHFS_USER }}
          SSHFS_PASS: ${{ secrets.SSHFS_PASS }}
        run: >
          rclone config create $RCLONE_NAME sftp
          --obscure
          host=stack.technicjelle.com
          user=$SSHFS_USER
          pass=$SSHFS_PASS
          shell_type=unix
      - name: Mount UE 5.4.4 install from a network drive
        run: >
          rclone mount $RCLONE_NAME:/ue/Linux_Unreal_Engine_5.4.4/
          ${{ env.RCLONE_MOUNT_POINT }}
          --file-perms 0777
          --daemon
      - name: List files in UE directory
        run: ls ${{ env.RCLONE_MOUNT_POINT }}
      - name: Create directory for staging files
        run: mkdir ${{ env.STAGING_DIR }}
      - name: chmod the RunUAT script
        run: chmod +x ${{ env.RCLONE_MOUNT_POINT }}/Engine/Build/BatchFiles/RunUAT.sh
      - name: Run UE5 build
        run: >
          ${{ env.RCLONE_MOUNT_POINT }}/Engine/Build/BatchFiles/RunUAT.sh -ScriptsForProject="$PWD/UE5_GHAction_VRTempl.uproject"
          BuildCookRun -project="$PWD/UE5_GHAction_VRTempl.uproject" -noP4
          -clientconfig=Shipping -serverconfig=Shipping -nocompile -nocompileeditor -installed
          -unrealexe="${{ env.RCLONE_MOUNT_POINT }}/Engine/Binaries/Linux/UnrealEditor-Cmd" -utf8output
          -platform=Linux -build -cook
          -allmaps -CookCultures=en -unversionedcookedcontent -pak -stage
          -stagingdirectory="${{ env.STAGING_DIR }}"
      - name: Unmount the network drive
        run: fusermount -u ${{ env.RCLONE_MOUNT_POINT }}
