name: Build

on:
  push:
  workflow_dispatch:

env:
  UE_IMAGE_URL: ghcr.io/epicgames/unreal-engine:dev-slim-5.4.4

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      # Free more space for the UE Docker Image
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          build-mount-path: /var/lib/docker/
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Restart docker
        run: sudo service docker restart

      - uses: actions/checkout@v4

      - name: Authenticate with GitHub Container Registry
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        run: echo $ACCESS_TOKEN | docker login ghcr.io -u $USERNAME --password-stdin
      - name: Docker Pull Prebuilt Container Image
        run: docker pull $UE_IMAGE_URL

      - name: Docker Run
        env:
          PROJECT_PATH: ${{ github.workspace }}
          COMMAND: /home/ue4/UnrealEngine/Engine/Build/BatchFiles/RunUAT.sh BuildCookRun -utf8output -platform=Linux -clientconfig=Shipping -serverconfig=Shipping -project=/project/UE5_GHAction_VRTempl.uproject -noP4 -nodebuginfo -allmaps -cook -build -stage -prereqs -pak -archive -archivedirectory=/project/Packaged
        run: docker run -v "$PROJECT_PATH:/project" $UE_IMAGE_URL $COMMAND

      - name: ls project directory
        run: ls

      - name: ls Packaged directory
        run: ls Packaged
